import { ThemeProvider } from "@/lib/utils/ThemeProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/component/layout/Navbar";
import { SearchProvider } from "@/provider/SearchContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <SearchProvider>
          <ThemeProvider>
            <Navbar />
            {children}
          </ThemeProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
